import { Injectable } from '@nestjs/common';
import type {
  GatherLeadsInput,
  LeadProvider,
  RawLeadCandidate,
} from '../interfaces/lead-provider.interface';

const MOCK_LEADS: RawLeadCandidate[] = [
  {
    businessName: 'Dublin Garden Revival',
    serviceType: 'landscaping',
    area: 'Dublin 6',
    phone: '+353 1 555 1101',
    email: 'info@dublingardenrevival.ie',
    website: 'https://dublingardenrevival.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/dgr-01',
    rating: 4.7,
    reviewCount: 84,
    description: 'Residential landscaping and full garden redesign.',
  },
  {
    businessName: 'Rathmines Outdoor Works',
    serviceType: 'landscaping',
    area: 'Rathmines',
    phone: '+353 1 555 1102',
    website: 'https://rathminesoutdoorworks.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/row-02',
    rating: 4.4,
    reviewCount: 39,
    description: 'Soft landscaping and patio planting projects.',
  },
  {
    businessName: 'Clontarf Stone Paving',
    serviceType: 'paving',
    area: 'Clontarf',
    phone: '+353 1 555 1201',
    email: 'hello@clontarfpaving.ie',
    website: 'https://clontarfpaving.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/csp-03',
    rating: 4.8,
    reviewCount: 102,
    description: 'Driveways, granite paving, and walkways.',
  },
  {
    businessName: 'Dublin 8 Driveway Pros',
    serviceType: 'paving',
    area: 'Dublin 8',
    phone: '+353 1 555 1202',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/d8p-04',
    rating: 4.1,
    reviewCount: 16,
    description: 'Block paving and domestic driveway repairs.',
  },
  {
    businessName: 'Southside Hedge Care',
    serviceType: 'hedge trimming',
    area: 'Dublin 6',
    phone: '+353 1 555 1301',
    email: 'bookings@southsidehedgecare.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/shc-05',
    rating: 4.6,
    reviewCount: 58,
    description: 'Seasonal hedge cutting and maintenance plans.',
  },
  {
    businessName: 'Ranelagh Hedge & Shrub',
    serviceType: 'hedge trimming',
    area: 'Ranelagh',
    phone: '+353 1 555 1302',
    website: 'https://ranelaghhedges.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/rhs-06',
    rating: 4.0,
    reviewCount: 12,
    description: 'Quick hedge and shrub shaping for homes.',
  },
  {
    businessName: 'PowerWash Dublin Central',
    serviceType: 'power washing',
    area: 'Dublin 2',
    phone: '+353 1 555 1401',
    email: 'quotes@powerwashdublincentral.ie',
    website: 'https://powerwashdublincentral.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/pdc-07',
    rating: 4.5,
    reviewCount: 74,
    description: 'Patios, facades, and driveway jet washing.',
  },
  {
    businessName: 'Docklands Pressure Clean',
    serviceType: 'power washing',
    area: 'Dublin 1',
    phone: '+353 1 555 1402',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/dpc-08',
    rating: 3.9,
    reviewCount: 9,
    description: 'Exterior pressure cleaning and sealing.',
  },
  {
    businessName: 'Templeogue Garden Tidy',
    serviceType: 'garden maintenance',
    area: 'Templeogue',
    phone: '+353 1 555 1501',
    email: 'team@templeoguegardentidy.ie',
    website: 'https://templeoguegardentidy.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/tgt-09',
    rating: 4.3,
    reviewCount: 51,
    description: 'Weekly mowing, seasonal cleanup, and upkeep.',
  },
  {
    businessName: 'Stillorgan Lawn & Leaf',
    serviceType: 'garden maintenance',
    area: 'Stillorgan',
    phone: '+353 1 555 1502',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/sll-10',
    rating: 4.2,
    reviewCount: 22,
    description: 'Lawn care, edging, and annual maintenance.',
  },
  {
    businessName: 'Leinster Tree Surgery',
    serviceType: 'tree surgery',
    area: 'Dublin 6',
    phone: '+353 1 555 1601',
    email: 'office@leinstertreesurgery.ie',
    website: 'https://leinstertreesurgery.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/lts-11',
    rating: 4.9,
    reviewCount: 133,
    description: 'Arborist services, pruning, and safe removals.',
  },
  {
    businessName: 'Sandyford Arbor Crew',
    serviceType: 'tree surgery',
    area: 'Sandyford',
    phone: '+353 1 555 1602',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/sac-12',
    rating: 4.4,
    reviewCount: 27,
    description: 'Commercial and residential tree surgery.',
  },
  {
    businessName: 'Dun Laoghaire Greenbuild',
    serviceType: 'landscaping',
    area: 'Dun Laoghaire',
    phone: '+353 1 555 1103',
    email: 'enquiries@dlgreenbuild.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/dlg-13',
    rating: 4.6,
    reviewCount: 63,
    description: 'Coastal garden landscaping and drainage solutions.',
  },
  {
    businessName: 'Firhouse Patio Makers',
    serviceType: 'paving',
    area: 'Firhouse',
    phone: '+353 1 555 1203',
    website: 'https://firhousepatiomakers.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/fpm-14',
    rating: 4.0,
    reviewCount: 11,
    description: 'Garden patios and decorative paving finishes.',
  },
  {
    businessName: 'Tallaght Hedge Masters',
    serviceType: 'hedge trimming',
    area: 'Tallaght',
    phone: '+353 1 555 1303',
    email: 'book@tallaghthedgemasters.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/thm-15',
    rating: 4.3,
    reviewCount: 24,
    description: 'Hedge shaping and overgrowth reduction.',
  },
  {
    businessName: 'Harolds Cross Wash Team',
    serviceType: 'power washing',
    area: 'Harolds Cross',
    phone: '+353 1 555 1403',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/hwt-16',
    rating: 4.7,
    reviewCount: 66,
    description: 'Driveway and wall pressure washing specialists.',
  },
  {
    businessName: 'Terenure Garden Care',
    serviceType: 'garden maintenance',
    area: 'Terenure',
    phone: '+353 1 555 1503',
    email: 'hello@terenuregardencare.ie',
    website: 'https://terenuregardencare.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/tgc-17',
    rating: 4.5,
    reviewCount: 77,
    description: 'Full-service garden maintenance for urban homes.',
  },
  {
    businessName: 'Cabinteely Tree & Stump',
    serviceType: 'tree surgery',
    area: 'Cabinteely',
    phone: '+353 1 555 1603',
    website: 'https://cabinteelytreeandstump.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/cts-18',
    rating: 4.1,
    reviewCount: 18,
    description: 'Tree pruning and stump grinding services.',
  },
  {
    businessName: 'Ballinteer Green Spaces',
    serviceType: 'landscaping',
    area: 'Ballinteer',
    phone: '+353 1 555 1104',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/bgs-19',
    rating: 4.2,
    reviewCount: 19,
    description: 'Landscaping with planting and garden edging.',
  },
  {
    businessName: 'Raheny Paving & Kerb',
    serviceType: 'paving',
    area: 'Raheny',
    phone: '+353 1 555 1204',
    email: 'sales@rahenypaving.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/rpk-20',
    rating: 4.6,
    reviewCount: 48,
    description: 'Kerbing, paving slabs, and driveway conversions.',
  },
  {
    businessName: 'Glasnevin Hedge Services',
    serviceType: 'hedge trimming',
    area: 'Glasnevin',
    phone: '+353 1 555 1304',
    website: 'https://glasnevinhedges.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/ghs-21',
    rating: 4.4,
    reviewCount: 36,
    description: 'Domestic hedge care and shrub maintenance.',
  },
  {
    businessName: 'Swords Exterior Cleaning',
    serviceType: 'power washing',
    area: 'Swords',
    phone: '+353 1 555 1404',
    email: 'contact@swordsexteriorcleaning.ie',
    website: 'https://swordsexteriorcleaning.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/sec-22',
    rating: 4.8,
    reviewCount: 89,
    description: 'Patio, render, and commercial forecourt cleaning.',
  },
  {
    businessName: 'Blackrock Garden Upkeep',
    serviceType: 'garden maintenance',
    area: 'Blackrock',
    phone: '+353 1 555 1504',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/bgu-23',
    rating: 3.8,
    reviewCount: 8,
    description: 'Affordable lawn and garden maintenance.',
  },
  {
    businessName: 'Howth Tree Professionals',
    serviceType: 'tree surgery',
    area: 'Howth',
    phone: '+353 1 555 1604',
    email: 'jobs@howthtreepros.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/htp-24',
    rating: 4.5,
    reviewCount: 55,
    description: 'High-access arborist work and hazard reductions.',
  },
  {
    businessName: 'Donnybrook Landscape Studio',
    serviceType: 'landscaping',
    area: 'Donnybrook',
    phone: '+353 1 555 1105',
    website: 'https://donnybrooklandscape.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/dls-25',
    rating: 4.9,
    reviewCount: 117,
    description: 'Premium landscaping and outdoor renovation.',
  },
  {
    businessName: 'Lucan Paving Solutions',
    serviceType: 'paving',
    area: 'Lucan',
    phone: '+353 1 555 1205',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/lps-26',
    rating: 4.3,
    reviewCount: 31,
    description: 'Paved paths, driveways, and maintenance.',
  },
  {
    businessName: 'Killiney Hedge Line',
    serviceType: 'hedge trimming',
    area: 'Killiney',
    phone: '+353 1 555 1305',
    email: 'info@killineyhedgeline.ie',
    website: 'https://killineyhedgeline.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/khl-27',
    rating: 4.7,
    reviewCount: 73,
    description: 'Precision hedge work and seasonal trimming rounds.',
  },
  {
    businessName: 'Malahide Jet Wash Co',
    serviceType: 'power washing',
    area: 'Malahide',
    phone: '+353 1 555 1405',
    website: 'https://malahidejetwash.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/mjw-28',
    rating: 4.2,
    reviewCount: 14,
    description: 'Jet washing for patios and stone surfaces.',
  },
  {
    businessName: 'Rathfarnham Garden Assist',
    serviceType: 'garden maintenance',
    area: 'Rathfarnham',
    phone: '+353 1 555 1505',
    email: 'support@rathfarnhamgardenassist.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/rga-29',
    rating: 4.6,
    reviewCount: 44,
    description: 'Scheduled mowing and seasonal tidy-up visits.',
  },
  {
    businessName: 'Dublin Hills Treecare',
    serviceType: 'tree surgery',
    area: 'Dublin 24',
    phone: '+353 1 555 1605',
    website: 'https://dublinhillstreecare.ie',
    source: 'mock',
    sourceUrl: 'https://mock.tradeez.local/leads/dht-30',
    rating: 4.0,
    reviewCount: 10,
    description: 'Tree assessments, pruning, and emergency call-outs.',
  },
];

@Injectable()
export class MockLeadProvider implements LeadProvider {
  async search(input: GatherLeadsInput): Promise<RawLeadCandidate[]> {
    const normalizedService = input.serviceType.trim().toLowerCase();
    const normalizedArea = input.area.trim().toLowerCase();

    const results = MOCK_LEADS.filter((lead) => {
      if (
        normalizedService &&
        !lead.serviceType.toLowerCase().includes(normalizedService)
      ) {
        return false;
      }

      if (normalizedArea && !lead.area.toLowerCase().includes(normalizedArea)) {
        return false;
      }

      if (
        input.minRating !== undefined &&
        (lead.rating === undefined || lead.rating < input.minRating)
      ) {
        return false;
      }

      if (
        input.minReviewCount !== undefined &&
        (lead.reviewCount === undefined ||
          lead.reviewCount < input.minReviewCount)
      ) {
        return false;
      }

      return true;
    });

    return results.slice(0, input.requestedCount);
  }
}
